# Generated by Django 3.1.5 on 2021-02-01 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recordings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_name', models.CharField(max_length=256)),
                ('blog_audio', models.FileField(blank=True, null=True, upload_to='recordings')),
            ],
        ),
    ]
